by_member: {}
by_period: {}
global: []
ng_dates:
  by_member:
    高橋良:
    - '2026-02-07'
    - '2025-02-08'
  by_period:
    例_メンバー名:
    - end: '2025-08-20'
      reason: 夏季休暇
      start: '2025-08-10'
  global:
  - '2025-12-27'
  - '2025-12-28'
  - '2025-12-29'
  - '2025-12-30'
  - '2025-12-31'
  - '2026-01-01'
  - '2026-01-02'
  - '2026-01-03'
  - '2026-01-04'
